#!/bin/sh
case $BUTTON in
	1) dmenu-audio-control ;; # Left click opens your widget
	3) amixer set Master toggle ;; # Right click mutes
	4) amixer set Master 5%+ ;;    # Scroll up
	5) amixer set Master 5%- ;;    # Scroll down
esac
