backend = "glx";
glx-copy-from-front = false;
detect-client-opacity = true;

blur: {
  method = "dual_kawase";
  strength = 6;
  background = true;
};

blur-background-exclude = [
  "role = 'xborder'",
  "_GTK_FRAME_EXTENTS@"
];